name: Testing stuff

on:
  push:
    branches:
      - testing

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Check health endpoint
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-dp.fly.dev/health